import { THEME } from '@/constants/theme';
import { StyleSheet } from 'react-native';

export const profileStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: THEME.bg,
    paddingHorizontal: 24,
  },
  center: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  card: {
    backgroundColor: THEME.card,
    padding: 32,
    borderRadius: 32,
    alignItems: 'center',
    marginBottom: 24,
    marginTop: 24,
    borderWidth: 1,
    borderColor: '#f1f5f9',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.05,
    shadowRadius: 15,
    elevation: 3,
  },
  name: {
    fontSize: 24,
    fontWeight: '800',
    color: THEME.text,
    letterSpacing: -0.5,
  },
  company: {
    fontSize: 15,
    color: THEME.muted,
    marginTop: 6,
    fontWeight: '500',
  },
  avatar: {
    width: 88,
    height: 88,
    borderRadius: 44,
    backgroundColor: THEME.primary,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 20,
    shadowColor: THEME.primary,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.3,
    shadowRadius: 12,
    elevation: 10,
  },
  avatarText: {
    color: 'white',
    fontSize: 32,
    fontWeight: '800',
  },
  detailsCard: {
    backgroundColor: THEME.card,
    padding: 24,
    borderRadius: 24,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: '#f1f5f9',
  },
  cardTitle: {
    fontWeight: '800',
    marginBottom: 16,
    fontSize: 18,
    color: THEME.text,
    letterSpacing: -0.3,
  },
  menuItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 14,
  },
  menuLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
  },
  menuText: {
    fontSize: 16,
    color: THEME.text,
    fontWeight: '600',
  },
  menuDivider: {
    height: 1,
    backgroundColor: '#f8fafc',
  },
  settingItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 14,
  },
  settingLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
  },
  settingRight: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  settingText: {
    fontSize: 16,
    color: THEME.text,
    fontWeight: '600',
  },
  settingValue: {
    fontSize: 14,
    color: THEME.muted,
    fontWeight: '500',
  },
  logoutButton: {
    backgroundColor: THEME.danger,
    padding: 18,
    borderRadius: 20,
    alignItems: 'center',
    marginTop: 16,
    marginBottom: 48,
    shadowColor: THEME.danger,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.25,
    shadowRadius: 12,
    elevation: 6,
  },
  logoutText: {
    color: 'white',
    fontWeight: '800',
    fontSize: 17,
    letterSpacing: 0.5,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(15, 23, 42, 0.6)',
    justifyContent: 'flex-end',
  },
  modalContent: {
    backgroundColor: THEME.card,
    borderTopLeftRadius: 32,
    borderTopRightRadius: 32,
    padding: 24,
    paddingBottom: 48,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 24,
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: '800',
    color: THEME.text,
    letterSpacing: -0.5,
  },
  languageOption: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 18,
    borderRadius: 16,
    backgroundColor: '#f8fafc',
    marginBottom: 12,
    borderWidth: 1.5,
    borderColor: 'transparent',
  },
  languageOptionActive: {
    backgroundColor: 'rgba(99, 102, 241, 0.08)',
    borderColor: THEME.primary,
  },
  languageText: {
    fontSize: 16,
    color: THEME.text,
    fontWeight: '600',
  },
  languageTextActive: {
    color: THEME.primary,
    fontWeight: '800',
  },
});
