import { THEME } from '@/constants/theme';
import { StyleSheet } from 'react-native';

export const requestsStyles = StyleSheet.create({
  center: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: THEME.bg,
  },
  header: {
    paddingHorizontal: 24,
    paddingTop: 32,
    paddingBottom: 24,
    backgroundColor: THEME.bg,
  },
  headerTitle: {
    fontSize: 28,
    fontWeight: '800',
    color: THEME.text,
    letterSpacing: -0.5,
  },
  listContainer: {
    paddingHorizontal: 24,
    paddingBottom: 120,
    gap: 12,
  },
  emptyContainer: {
    flex: 1,
    paddingVertical: 100,
    justifyContent: 'center',
    alignItems: 'center',
  },
  emptyContent: {
    alignItems: 'center',
    backgroundColor: THEME.card,
    padding: 32,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: '#f1f5f9',
    width: '100%',
  },
  emptyText: {
    marginTop: 16,
    fontSize: 16,
    color: THEME.muted,
    fontWeight: '600',
  },
  fab: {
    position: 'absolute',
    right: 24,
    bottom: 32,
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: THEME.primary,
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 8,
    shadowColor: THEME.primary,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.35,
    shadowRadius: 15,
  },
  modalContainer: {
    flex: 1,
    backgroundColor: THEME.bg,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 24,
    paddingVertical: 20,
    backgroundColor: THEME.card,
    borderBottomWidth: 1,
    borderBottomColor: '#f1f5f9',
  },
  modalCancel: {
    fontSize: 16,
    color: THEME.primary,
    fontWeight: '700',
  },
  modalHeaderTitle: {
    fontSize: 18,
    fontWeight: '800',
    color: THEME.text,
    letterSpacing: -0.3,
  },
});
